In [1]:
import nltk
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

example = "The cat was chasing the mice"
example = [stemmer.stem(token) for token in example.split(" ")]

In [2]:
print(" ".join(example))

the cat wa chase a mous


In [3]:
import nltk
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

example = "The cat was chasing the mice"
example = [stemmer.stem(token) for token in example.split(" ")]

In [4]:
print(" ".join(example))

the cat wa chase the mice


In [7]:
import nltk
from nltk.stem import WordNetLemmatizer
stemmer = WordNetLemmatizer()

example = "The cat was chasing the mice"
example = [stemmer.lemmatize(token) for token in example.split(" ")]

In [8]:
print(" ".join(example))

The cat wa chasing the mouse


In [10]:
print(stemmer.lemmatize('better', pos = 'a'))

good


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine ","optical character recognition is significant "]
vect.fit(corpus)
print(vect.transform(["Today is good optical"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [7]:
vocab = vect.vocabulary_
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [19]:
from sklearn.feature_extraction.text import TfidVectorizer

ImportError: cannot import name 'TfidVectorizer' from 'sklearn.feature_extraction.text' (C:\Users\anshj\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(["tessaract is an optical character recognition engine", "optical character recognition is significant"]))
print(similarity)

[[1.         0.73029674]
 [0.73029674 1.        ]]


In [2]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(["One of the finer books I read this year was John Kaag's Hiking with nietzsche in which Kaag, a professor of philosophy, rekindles is passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. Its a near-precise rendering of the travelogue as a self-help book. A young cat was an avowed Nietzsche acolyte but given the ravages of resposibilities and adulthood, the writer put his affinity to test by undertaking physically and enduring hikes through the Alphs, revisiting haunds that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own inner turmoil, are catnip for anybody feeling at cross purposes with thier own life.", "
Summer is a charming flirt. Easy-going and casual. Summer doesn't huff and puff to win our affections. It has us at Hello. Winter broods like the torchered protagonist of big fat Russian novel. It is daunting and dramatic, burning with a slow intensity."]))
print(similarity)

SyntaxError: EOL while scanning string literal (<ipython-input-2-c822969f5ffd>, line 2)

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(["One of the finer books I read this year was John Kaag's Hiking with nietzsche in which Kaag, a professor of philosophy, rekindles is passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. Its a near-precise rendering of the travelogue as a self-help book. A young cat was an avowed Nietzsche acolyte but given the ravages of resposibilities and adulthood, the writer put his affinity to test by undertaking physically and enduring hikes through the Alphs, revisiting haunds that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own inner turmoil, are catnip for anybody feeling at cross purposes with thier own life.",
                                               "Summer is a charming flirt. Easy-going and casual. Summer does not huff and puff to win our affections. It has us at Hello. Winter broods like the torchered protagonist of big fat Russian novel. It is daunting and dramatic, burning with a slow intensity."]))
print(similarity)

[[1. 1.]
 [1. 1.]]


In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
vect = CountVectorizer(binary = True)
corpus = ["""If there is a phrase I would prefer to retire from online bios, personal or professional, it is, “I love travel.” Or some approximation of that sentiment. To clarify, I am not against travellers or those who proudly flaunt their passion for travel. On the contrary, editing a travel magazine has now made me oddly protective of travellers and their ilk. My submission is that “love to travel,” suggested so casually, just doesn’t feel adequate to the depth of emotion it sparks in true devotees. ""","""One of the finer books I read this year was John Kaag's Hiking with nietzsche in which Kaag, a professor of philosophy, rekindles is passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. Its a near-precise rendering of the travelogue as a self-help book. A young cat was an avowed Nietzsche acolyte but given the ravages of resposibilities and adulthood, the writer put his affinity to test by undertaking physically and enduring hikes through the Alphs, revisiting haunds that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own inner turmoil, are catnip for anybody feeling at cross purposes with thier own life."""]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect.transform(["One of the finer books I read this year was John Kaag's Hiking with nietzsche in which Kaag, a professor of philosophy, rekindles is passion for the German thinker while tracing picturesque hiking trails in the mountains of Switzerland. Its a near-precise rendering of the travelogue as a self-help book. A young cat was an avowed Nietzsche acolyte but given the ravages of resposibilities and adulthood, the writer put his affinity to test by undertaking physically and enduring hikes through the Alphs, revisiting haunds that the philosopher escaped to, in search of solitude and salve. The journey's demands, coupled with his own inner turmoil, are catnip for anybody feeling at cross purposes with thier own life.",
                                               "Summer is a charming flirt. Easy-going and casual. Summer does not huff and puff to win our affections. It has us at Hello. Winter broods like the torchered protagonist of big fat Russian novel. It is daunting and dramatic, burning with a slow intensity."]))
print(similarity)

[[1.         0.23869802]
 [0.23869802 1.        ]]
